-- R4 slice 2: delivery WorkItem aggregate + Team WorkItem Workflow (doc 27:98-146,
-- 30:259-260, 23:118-119). Same tenant model as slice 1: composite (organization_id,
-- id) keys + composite FKs so a child can never reference a parent in another org,
-- and the permissive tenant_isolation + restrictive tenant_boundary_guard + FORCE
-- RLS pair keyed on pie.organization_id.
--
-- Two-workflow boundary (doc 27:137-146): these tables model ONLY the Team WorkItem
-- Workflow (execution states Todo→In Progress→…). The Project Delivery Workflow
-- (stage approvals) is a separate concept and is NOT created or coupled here.

-- A per-team workflow version: bumped whenever the team's state SET changes so a
-- board move carrying a stale workflowVersion is rejected (doc 23:118-119). Distinct
-- from teams.version (the team resource's own optimistic-concurrency counter).
alter table delivery.teams
  add column workflow_version bigint not null default 1;

-- delivery.workflow_states: the team-owned WorkItem Workflow states. category is
-- fixed vocabulary; key/name are team-defined. The extra unique(organization_id,
-- team_id, id) lets work_items FK on (organization_id, team_id, state_id) so a work
-- item's state must belong to its OWN team, not merely the same org.
create table delivery.workflow_states (
  organization_id uuid not null,
  id uuid not null default gen_random_uuid(),
  team_id uuid not null,
  key text not null,
  name text not null,
  category text not null,
  sort_key bigint not null,
  created_at timestamptz not null default now(),
  primary key (organization_id, id),
  constraint workflow_states_team_key_unique unique (organization_id, team_id, key),
  constraint workflow_states_team_id_unique unique (organization_id, team_id, id),
  constraint workflow_states_category_check
    check (category in ('triage', 'backlog', 'unstarted', 'started', 'completed', 'canceled')),
  constraint workflow_states_key_pattern check (key ~ '^[a-z][a-z0-9_]{1,29}$'),
  constraint workflow_states_team_fk
    foreign key (organization_id, team_id) references delivery.teams (organization_id, id)
    on delete cascade
);

create index workflow_states_team_idx
  on delivery.workflow_states (organization_id, team_id, sort_key);

-- delivery.work_items: the aggregate. teamId REQUIRED, projectId NULLABLE (personal
-- / team backlog). The human identifier (team.key + '-' + sequence, e.g. APP-142) is
-- generated by incrementing delivery.team_counters IN THE creating transaction; it is
-- a distinct namespace from Orca's Worktree/Workspace/task IDs (roadmap 14:671-682)
-- and is NOT the primary key — the opaque UUID id is.
create table delivery.work_items (
  organization_id uuid not null,
  id uuid not null default gen_random_uuid(),
  team_id uuid not null,
  project_id uuid,
  sequence bigint not null,
  identifier text not null,
  title text not null,
  description text,
  state_id uuid not null,
  workflow_version bigint not null,
  assignee_id uuid,
  creator_id uuid not null,
  priority text not null default 'none',
  sort_key bigint not null,
  version bigint not null default 1,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (organization_id, id),
  constraint work_items_team_sequence_unique unique (organization_id, team_id, sequence),
  constraint work_items_identifier_unique unique (organization_id, identifier),
  constraint work_items_priority_check
    check (priority in ('none', 'urgent', 'high', 'medium', 'low')),
  constraint work_items_identifier_pattern check (identifier ~ '^[A-Z][A-Z0-9]{1,9}-[1-9][0-9]*$'),
  constraint work_items_team_fk
    foreign key (organization_id, team_id) references delivery.teams (organization_id, id)
    on delete cascade,
  constraint work_items_project_fk
    foreign key (organization_id, project_id) references delivery.projects (organization_id, id)
    on delete set null,
  -- The state must be one of the item's OWN team's workflow states (same-team FK).
  constraint work_items_state_fk
    foreign key (organization_id, team_id, state_id)
    references delivery.workflow_states (organization_id, team_id, id)
);

create index work_items_team_idx
  on delivery.work_items (organization_id, team_id, sort_key)
  where archived_at is null;

create index work_items_project_idx
  on delivery.work_items (organization_id, project_id)
  where project_id is not null and archived_at is null;

-- === RLS: the standard tenant pair on the new delivery tables ===
do $$
declare
  t text;
begin
  foreach t in array array['workflow_states', 'work_items']
  loop
    execute format('alter table delivery.%I enable row level security', t);
    execute format('alter table delivery.%I force row level security', t);
    execute format(
      'create policy %I on delivery.%I as permissive for all to pie_app '
      || 'using (organization_id = nullif(current_setting(''pie.organization_id'', true), '''')::uuid) '
      || 'with check (organization_id = nullif(current_setting(''pie.organization_id'', true), '''')::uuid)',
      t || '_tenant_isolation', t);
    execute format(
      'create policy %I on delivery.%I as restrictive for all to pie_app '
      || 'using (organization_id = nullif(current_setting(''pie.organization_id'', true), '''')::uuid) '
      || 'with check (organization_id = nullif(current_setting(''pie.organization_id'', true), '''')::uuid)',
      t || '_tenant_boundary_guard', t);
    execute format('grant select, insert, update, delete on delivery.%I to pie_app', t);
  end loop;
end
$$;
